[2024-05-28T17:22:55.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T17:22:55.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T17:22:51.794798+00:00 [queued]>
[2024-05-28T17:22:55.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T17:22:51.794798+00:00 [queued]>
[2024-05-28T17:22:55.660+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T17:22:55.672+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_extraction> on 2024-05-28 17:22:51.794798+00:00
[2024-05-28T17:22:55.681+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T17:22:55.682+0000] {standard_task_runner.py:63} INFO - Started process 56 to run task
[2024-05-28T17:22:55.682+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_extraction', 'manual__2024-05-28T17:22:51.794798+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmphnynvo64']
[2024-05-28T17:22:55.684+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask data_extraction
[2024-05-28T17:22:55.696+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T17:22:55.723+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_extraction manual__2024-05-28T17:22:51.794798+00:00 [running]> on host 03b4db1c7961
[2024-05-28T17:22:55.808+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T17:22:51.794798+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T17:22:51.794798+00:00'
[2024-05-28T17:22:55.810+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T17:22:55.822+0000] {sales_data_pipeline.py:45} INFO - data_extraction started
[2024-05-28T17:23:05.929+0000] {sales_data_pipeline.py:49} ERROR - Error in data_extraction
Traceback (most recent call last):
  File "/opt/airflow/dags/sales_data_pipeline.py", line 46, in data_extraction
    process_Ecommrese_data()
  File "/opt/airflow/dags/scripts/transform_data.py", line 10, in process_Ecommrese_data
    df['Order Date'] = pd.to_datetime([df['Order Date']])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 1100, in to_datetime
    result = convert_listlike(argc, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/datetimes.py", line 395, in _convert_listlike_datetimes
    raise TypeError(
TypeError: arg must be a string, datetime, list, tuple, 1-d array, or Series
[2024-05-28T17:23:05.934+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T17:23:05.935+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T17:23:05.944+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_extraction, run_id=manual__2024-05-28T17:22:51.794798+00:00, execution_date=20240528T172251, start_date=20240528T172255, end_date=20240528T172305
[2024-05-28T17:23:05.985+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T17:23:06.004+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T17:23:06.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
