[2024-05-28T22:26:04.410+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:26:04.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:25:48.384416+00:00 [queued]>
[2024-05-28T22:26:04.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:25:48.384416+00:00 [queued]>
[2024-05-28T22:26:04.439+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-28T22:26:04.451+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-05-28 22:25:48.384416+00:00
[2024-05-28T22:26:04.460+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T22:26:04.461+0000] {standard_task_runner.py:63} INFO - Started process 320 to run task
[2024-05-28T22:26:04.462+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'data_delivery', 'manual__2024-05-28T22:25:48.384416+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/sales_data_pipeline.py', '--cfg-path', '/tmp/tmpw1ck7mfr']
[2024-05-28T22:26:04.464+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask data_delivery
[2024-05-28T22:26:04.474+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-28T22:26:04.502+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.data_delivery manual__2024-05-28T22:25:48.384416+00:00 [running]> on host 90e12a9d37bb
[2024-05-28T22:26:04.582+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud Mamdoh' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:25:48.384416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:25:48.384416+00:00'
[2024-05-28T22:26:04.583+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:26:04.595+0000] {sales_data_pipeline.py:54} INFO - data_delivery started
[2024-05-28T22:26:04.596+0000] {Load_data.py:10} INFO - Loading customer_df dimension...
[2024-05-28T22:26:04.603+0000] {tables_creation.py:47} INFO - Loading data into table DIM_CUSTOMERS...
[2024-05-28T22:26:04.607+0000] {db_utils.py:20} INFO - Connected to PostgreSQL database successfully
[2024-05-28T22:26:04.909+0000] {tables_creation.py:59} INFO - Data loaded successfully into table DIM_CUSTOMERS
[2024-05-28T22:26:04.910+0000] {db_utils.py:29} INFO - PostgreSQL connection is closed
[2024-05-28T22:26:04.910+0000] {Load_data.py:16} INFO - customer_df dimension loaded successfully
[2024-05-28T22:26:04.918+0000] {Load_data.py:23} INFO - Loading customer dimension...
[2024-05-28T22:26:04.922+0000] {tables_creation.py:47} INFO - Loading data into table DIM_STORE...
[2024-05-28T22:26:04.926+0000] {db_utils.py:20} INFO - Connected to PostgreSQL database successfully
[2024-05-28T22:26:05.782+0000] {tables_creation.py:59} INFO - Data loaded successfully into table DIM_STORE
[2024-05-28T22:26:05.782+0000] {db_utils.py:29} INFO - PostgreSQL connection is closed
[2024-05-28T22:26:05.783+0000] {Load_data.py:29} INFO - store_df dimension loaded successfully
[2024-05-28T22:26:05.799+0000] {Load_data.py:36} INFO - Loading customer dimension...
[2024-05-28T22:26:05.815+0000] {tables_creation.py:47} INFO - Loading data into table DIM_PRODUCT...
[2024-05-28T22:26:05.819+0000] {db_utils.py:20} INFO - Connected to PostgreSQL database successfully
[2024-05-28T22:26:07.839+0000] {tables_creation.py:59} INFO - Data loaded successfully into table DIM_PRODUCT
[2024-05-28T22:26:07.839+0000] {db_utils.py:29} INFO - PostgreSQL connection is closed
[2024-05-28T22:26:07.840+0000] {Load_data.py:42} INFO - product_df dimension loaded successfully
[2024-05-28T22:26:07.889+0000] {Load_data.py:49} INFO - Loading fact sales ...
[2024-05-28T22:26:07.982+0000] {tables_creation.py:47} INFO - Loading data into table FACT_SALES...
[2024-05-28T22:26:07.985+0000] {db_utils.py:20} INFO - Connected to PostgreSQL database successfully
[2024-05-28T22:26:19.994+0000] {tables_creation.py:59} INFO - Data loaded successfully into table FACT_SALES
[2024-05-28T22:26:19.995+0000] {db_utils.py:29} INFO - PostgreSQL connection is closed
[2024-05-28T22:26:20.325+0000] {Load_data.py:53} INFO - Sales fact loaded successfully
[2024-05-28T22:26:20.328+0000] {sales_data_pipeline.py:59} INFO - data_delivery done
[2024-05-28T22:26:20.328+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T22:26:20.329+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:26:20.338+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=data_delivery, run_id=manual__2024-05-28T22:25:48.384416+00:00, execution_date=20240528T222548, start_date=20240528T222604, end_date=20240528T222620
[2024-05-28T22:26:20.365+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T22:26:20.378+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:26:20.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
